//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class up07Entities : DbContext
    {
        public up07Entities()
            : base("name=up07Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<анализы> анализы { get; set; }
        public virtual DbSet<врачи> врачи { get; set; }
        public virtual DbSet<заведующие> заведующие { get; set; }
        public virtual DbSet<медицинские_карты> медицинские_карты { get; set; }
        public virtual DbSet<отделения> отделения { get; set; }
        public virtual DbSet<пациенты> пациенты { get; set; }
        public virtual DbSet<полиcа_ОМС> полиcа_ОМС { get; set; }
        public virtual DbSet<пользователи> пользователи { get; set; }
        public virtual DbSet<приемы> приемы { get; set; }
        public virtual DbSet<рецепты> рецепты { get; set; }
        public virtual DbSet<роли> роли { get; set; }
        public virtual DbSet<специальности> специальности { get; set; }
        public virtual DbSet<страховые_компании> страховые_компании { get; set; }
    }
}
