//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class анализы
    {
        public int анализ_ид { get; set; }
        public int пациент_ид { get; set; }
        public int врач_ид { get; set; }
        public string тип_теста { get; set; }
        public System.DateTime дата_анализа { get; set; }
        public string результат { get; set; }
    
        public virtual врачи врачи { get; set; }
        public virtual пациенты пациенты { get; set; }
    }
}
