//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class медицинские_карты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public медицинские_карты()
        {
            this.рецепты = new HashSet<рецепты>();
        }
    
        public int медицинская_карта_ид { get; set; }
        public int пациент_ид { get; set; }
        public int врач_ид { get; set; }
        public System.DateTime дата_приема { get; set; }
        public string жалобы { get; set; }
        public string история_болезней { get; set; }
        public string диагнозы { get; set; }
        public string лечение { get; set; }
    
        public virtual врачи врачи { get; set; }
        public virtual пациенты пациенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<рецепты> рецепты { get; set; }
    }
}
