//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class пациенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пациенты()
        {
            this.анализы = new HashSet<анализы>();
            this.медицинские_карты = new HashSet<медицинские_карты>();
            this.полиcа_ОМС = new HashSet<полиcа_ОМС>();
            this.приемы = new HashSet<приемы>();
        }
    
        public int пациент_ид { get; set; }
        public int пользователь_ид { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public string пол { get; set; }
        public int СНИЛС { get; set; }
        public int полис_ОМС { get; set; }
        public string адрес { get; set; }
        public int телефон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<анализы> анализы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<медицинские_карты> медицинские_карты { get; set; }
        public virtual пользователи пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<полиcа_ОМС> полиcа_ОМС { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<приемы> приемы { get; set; }
    }
}
