//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class полиcа_ОМС
    {
        public int полис_ОМС_ид { get; set; }
        public int пациент_ид { get; set; }
        public int страховая_компания_ид { get; set; }
        public int серия_номер_бланка { get; set; }
        public System.DateTime дата_начала { get; set; }
        public System.DateTime дата_окончания { get; set; }
        public int номер_полиса { get; set; }
    
        public virtual пациенты пациенты { get; set; }
        public virtual страховые_компании страховые_компании { get; set; }
    }
}
