//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class приемы
    {
        public int прием_ид { get; set; }
        public int пациент_ид { get; set; }
        public int врач_ид { get; set; }
        public System.DateTime дата_приема { get; set; }
        public string тип_приема { get; set; }
        public string диагноз { get; set; }
        public string рекомендации { get; set; }
        public string направление { get; set; }
    
        public virtual врачи врачи { get; set; }
        public virtual пациенты пациенты { get; set; }
    }
}
