//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up07
{
    using System;
    using System.Collections.Generic;
    
    public partial class рецепты
    {
        public int рецепт_ид { get; set; }
        public int медицинская_карта_ид { get; set; }
        public string препарат { get; set; }
        public string дозировка { get; set; }
        public string способ_применения { get; set; }
        public System.DateTime срок { get; set; }
    
        public virtual медицинские_карты медицинские_карты { get; set; }
    }
}
